### PR TITLE
User service migration

### LINKED ISSUE #12: `user` microservice
https://github.com/pgressa/oraclecloud-cloudnative/tree/master/src/user

### PR DESCRIPTION
**Pull request by dstepanov**
Fixes #12

### CODE REVIEW

**Comment by pgressa** [comment]
@dstepanov sorry forced pushed to your commit

**Comment by dstepanov** [comment]
@pgressa You removed my second commit

**Comment by pgressa** [comment]
ok so force push back, I'll reflog

**Comment by dstepanov** [comment]
I will rebase on your changes

**Pull request merged**
